USE SALVADORA;
describe PRODUCTO;
INSERT INTO PRODUCTO
(COD_PRODUCTO,NOMBRE,MARCA,COLOR,MODELO,STOCK,PRECIO)
values
(100,"TOSTADORA","OSTER","ROJO","RT-8","34","1200"),
(null,"LAVADORA","LG","GRIS","RT-7","20","23000");
SELECT * FROM PRODUCTO;